# New ports collection makefile for:	gnome-devel-docs
# Date created:		2007-09-18
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/misc/gnome-devel-docs3/Makefile,v 1.8 2011/10/13 11:03:50 kwm Exp $
#

PORTNAME=	gnome-devel-docs
PORTVERSION=	3.2.1
CATEGORIES=	misc gnome
MASTER_SITES=	GNOME
DIST_SUBDIR=	gnome3

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Documents targeted for GNOME developers

CONFLICTS=	gnome-devel-docs-2.[0-9]*

LATEST_LINK=	gnome-devel-docs3
USE_XZ=	yes
GNU_CONFIGURE=	yes
USE_GMAKE=	yes
USE_GNOME=	gnomehier gnomedocutils
INSTALLS_OMF=	yes

.include <bsd.port.mk>
