# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD$
#   $MCom: ports/trunk/x11/gnome3-lite/Makefile 17268 2013-04-01 05:13:11Z marcus $

PORTREVISION=	0
CATEGORIES=	x11 gnome
PKGNAMESUFFIX=	-lite

COMMENT=	The "meta-port" of the GNOME desktop slimmed down for only the basics

MASTERDIR=	${.CURDIR}/../gnome3
CONFLICTS=	gnome2-[0-9]* gnome2-lite-[0-9]* gnome3-[0-9]*

DESCR=		${.CURDIR}/pkg-descr
PKGMESSAGE=	${.CURDIR}/pkg-message

.include "${MASTERDIR}/Makefile"
