# New ports collection makefile for:	gstreamer-plugins-polypaudio
# Date created:			8 Dec 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-polypaudio80/Makefile,v 1.1 2006/01/20 02:55:53 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	Gstreamer polypaudio sound server plugin

GST_PLUGIN=	polypaudio

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
