# New ports collection makefile for:	gstreamer-plugins-gsm
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-gsm/Makefile,v 1.4 2008/03/15 21:09:28 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer gsm encoding/decoding plugin

GST_PLUGIN=	gsm

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
