# New ports collection makefile for:	gstreamer-plugins-gsm
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-gsm/Makefile,v 1.3 2008/02/21 15:33:16 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer gsm encoding/decoding plugin

GST_PLUGIN=	gsm

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
