# Created by: Michael Johnson <ahze@FreeBSD.org>
# $FreeBSD$
#   $MCom$

PORTNAME=	shared-color-profiles
PORTVERSION=	0.1.5
CATEGORIES=	graphics
MASTER_SITES=	http://people.freedesktop.org/~hughsient/releases/

MAINTAINER=	ahze@FreeBSD.org
COMMENT=	Color profiles from contributors for color calibration

GNU_CONFIGURE=	yes

.include <bsd.port.mk>
