# New ports collection makefile for:	gstreamer-plugins-neon
# Date created:			6 July 2006
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/www/gstreamer-plugins-neon/Makefile,v 1.4 2008/03/15 21:09:38 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	www

COMMENT=	Gstreamer neon plugin

GST_PLUGIN=	neon

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
