# New ports collection makefile for:	gstreamer-plugins-cdaudio
# Date created:			22 Dec 2006
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-cdaudio/Makefile,v 1.4 2008/03/15 21:09:27 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer frontend to libcdaudio

GST_PLUGIN=	cdaudio

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
