# New ports collection makefile for:	gstreamer-plugins-wavpack
# Date created:			5 July 2005
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-wavpack/Makefile,v 1.2 2008/03/15 21:09:31 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	audio

GST_PLUGIN=	wavpack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
