# New ports collection makefile for:	gstreamer-plugins-wavpack
# Date created:			5 July 2005
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-wavpack/Makefile,v 1.1 2008/02/21 16:27:59 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	audio

GST_PLUGIN=	wavpack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
