# New ports collection makefile for:	gir-repository-babl
# Date created:				12 September 2009
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	x11

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-babl

.include "${MASTERDIR}/bsd.gir.mk"
