# New ports collection makefile for:	gstreamer-plugins-dvd
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/multimedia/gstreamer-plugins-dvd/Makefile,v 1.5 2008/02/21 14:20:38 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer dvd plugin set

GST_PLUGIN=	dvd

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
