# New ports collection makefile for:	gir-repository-webkit
# Date created:				07 September 2009
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	www

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-webkit

.include "${MASTERDIR}/bsd.gir.mk"
