# $FreeBSD$

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer dv plugin

GST_PLUGIN=	libdv
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
