# New ports collection makefile for:	epiphany-webkit
# Date created:		2007-10-21
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/www/epiphany-webkit/Makefile,v 1.6 2008/04/21 00:10:58 marcus Exp $

PORTVERSION=	3
PKGNAMESUFFIX=	-webkit

COMMENT=	 An extremely lightweight GNOME browser using the WebKit engine

EPHY_SLAVE=	webkit
MASTERDIR=	${.CURDIR}/../../www/epiphany

.include "${MASTERDIR}/Makefile"
