# New ports collection makefile for:	gstreamer-plugins-jack
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-jack80/Makefile,v 1.1 2006/01/20 02:55:51 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	Gstreamer low-latency audio server plugin

GST_PLUGIN=	jack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
