# New ports collection makefile for:	gstreamer-plugins-hal
# Date created:			16 May 2006
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD
#    $MCom$
#

CATEGORIES=	sysutils
PORTREVISION=	0

COMMENT=	Gstreamer hal plugin

GST_PLUGIN=	hal

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
