# New ports collection makefile for:	gstreamer-plugins-hal
# Date created:			16 May 2006
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/sysutils/gstreamer-plugins-hal/Makefile,v 1.5 2008/03/15 21:09:37 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	sysutils

COMMENT=	Gstreamer hal plugin

GST_PLUGIN=	hal

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
