# New ports collection makefile for:	gstreamer-plugins-soundtouch
# Date created:			15 Feb 2008
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	audio
PORTREVISION=	0

COMMENT=	GStreamer soundtouch plugin

GST_PLUGIN=	soundtouch

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
