# New ports collection makefile for:	gstreamer-plugins-soundtouch
# Date created:			15 Feb 2008
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-soundtouch/Makefile,v 1.2 2008/03/15 21:09:30 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	GStreamer soundtouch plugin

GST_PLUGIN=	soundtouch

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
