# New ports collection makefile for:	gstreamer-plugins-libcaca
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/graphics/gstreamer-plugins-libcaca/Makefile,v 1.3 2008/02/21 16:27:56 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	graphics

COMMENT=	Gstreamer color ascii art plugin

GST_PLUGIN=	libcaca

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
