# Created by: Michael Nottebrock <lofi@FreeBSD.org>
# $FreeBSD$
#   $MCom: ports/graphics/poppler-utils/Makefile,v 1.7 2012/06/13 12:29:04 kwm Exp $

PORTREVISION=	0
PKGNAMESUFFIX=	-utils

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Poppler's xpdf-workalike command line utilities

MASTERDIR=	${.CURDIR}/../../graphics/poppler
SLAVEPORT=	utils
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
