# New ports collection makefile for:	hal-device-manager
# Date created:		2006-05-18
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$

PORTREVISION=	0
CATEGORIES=	sysutils gnome
PKGNAMESUFFIX=	-device-manager

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	HAL device manager

SLAVE_PORT=	yes

MASTERDIR=	${.CURDIR}/../../sysutils/hal
PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
