# New ports collection makefile for:	gstreamer-plugins-ladspa
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-ladspa80/Makefile,v 1.1 2006/01/20 02:55:52 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	Gstreamer ladspa (Linux Audio Developer's Simple Plugin API) plugin

GST_PLUGIN=	ladspa

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
