# New ports collection makefile for:	gstreamer-plugins-mpeg2enc
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/multimedia/gstreamer-plugins-mpeg2enc/Makefile,v 1.3 2008/02/21 15:33:17 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer mpeg encoder plugin

GST_PLUGIN=	mpeg2enc

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
