# New ports collection makefile for:	gstreamer-plugins-jpeg-mmx
# Date created:			1 Nov 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/gstreamer-plugins-jpeg-mmx80/Makefile,v 1.1 2006/01/20 02:56:01 ahze Exp $
#

CATEGORIES=	graphics
PORTREVISION=	2

COMMENT=	Gstreamer jpeg encoder/decoder plugin with mmx optimalizations

GST_PLUGIN=	jpeg-mmx

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
