# New ports collection makefile for:	gstreamer-plugins-musepack
# Date created:			4 Dec 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-musepack/Makefile,v 1.3 2008/02/21 15:33:17 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer musepack mpc encoder/decoder plugin

GST_PLUGIN=	musepack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
