# New ports collection makefile for:	fontilus
# Date created:		15 February 2003
# Whom:			Joe Marcus Clarke <marcus@FreeBSD.org>
#
# $FreeBSD: ports/x11-fonts/fontilus/Makefile,v 1.3 2003/02/26 07:31:10 marcus Exp $
#

PORTNAME=	fontilus
PORTVERSION=	0.4
CATEGORIES=	x11-fonts x11-fm
MASTER_SITES=	${MASTER_SITE_GNOME}
MASTER_SITE_SUBDIR=	sources/${PORTNAME}/0.4
DIST_SUBDIR=	gnome2

MAINTAINER=	marcus@FreeBSD.org
COMMENT=	A font view for Nautilus

USE_BZIP2=	yes
USE_GNOME=	gnomehack gnomeprefix nautilus2
GNOME_DESKTOP_VERSION=2
USE_X_PREFIX=	yes
USE_GMAKE=	yes
USE_LIBTOOL=	yes

.include <bsd.port.mk>
