# New ports collection makefile for:	gstreamer-plugins-nas
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-nas80/Makefile,v 1.1 2006/01/20 02:55:53 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	GStreamer NAS (Network Audio System) plugin

GST_PLUGIN=	nas

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
