# New ports collection makefile for:	gutenprint-cups
# Date created:		2007-03-27
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$

PORTREVISION=	0
PORTEPOCH=	0
PKGNAMESUFFIX=	-cups

MAINTAINER=	ahze@FreeBSD.org
COMMENT=	GutenPrint CUPS drivers

MASTERDIR=	${.CURDIR}/../../print/gutenprint-base

GUT_SLAVE=	cups
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
