#!/bin/sh

if [ "$2" = "POST-INSTALL" ]; then
    dirs="etc/gconf/gconf.xml.defaults/apps \
    	etc/gconf/gconf.xml.defaults/schemas/apps \
	etc/gconf/schemas"
    for i in ${dirs}; do
	mkdir -p ${PKG_PREFIX}/${i}
    done
fi

exit 0
