# New ports collection makefile for:	gstreamer-plugins-wavpack
# Date created:			5 July 2005
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	audio
PORTREVISION=	1

GST_PLUGIN=	wavpack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
