# New ports collection makefile for:	gstreamer-plugins-wavpack
# Date created:			5 July 2005
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-wavpack80/Makefile,v 1.1 2006/01/20 02:55:55 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

GST_PLUGIN=	wavpack

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
