# New ports collection makefile for:	freedesktop-sound-theme
# Date created:				15 August 2008
# Whom:					Joe Marcus Clarke <marcus@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/freedesktop-sound-theme/Makefile,v 1.5 2009/11/26 20:51:55 kwm Exp $
#

PORTNAME=	freedesktop-sound-theme
PORTVERSION=	0.7
CATEGORIES=	audio gnome
MASTER_SITES=	LOCAL
MASTER_SITE_SUBDIR=	kwm
DISTNAME=	sound-theme-freedesktop-${PORTVERSION}

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Sound theme based on the FreeDesktop specification

USE_BZIP2=	yes
USE_GNOME=	gnomehier intlhack
USE_GETTEXT=	yes
USE_GMAKE=	yes
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
