# New ports collection makefile for:	gutenprint-gimp
# Date created:		2006-12-31
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$

PORTREVISION=	0
PORTEPOCH=	0
PKGNAMEPREFIX=	gimp-

MAINTAINER=	ahze@FreeBSD.org
COMMENT=	Gimp print plug-in

MASTERDIR=	${.CURDIR}/../../print/gutenprint

BUILD_WRKSRC=	${WRKSRC}/src/gimp2
INSTALL_WRKSRC=	${WRKSRC}/src/gimp2

PLIST=	# empty
PLIST_FILES=	libexec/gimp/2.2/plug-ins/print

.include "${MASTERDIR}/Makefile"
