# New ports collection makefile for:	gir-repository-avahi
# Date created:				12 September 2009
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	net

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-avahi

.include "${MASTERDIR}/bsd.gir.mk"
