# New ports collection makefile for:	gstreamer-plugins-gnomevfs
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	devel
PORTREVISION=	1

COMMENT=	Gstreamer gnomevfs plugin

GST_PLUGIN=	gnomevfs

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
