# $FreeBSD$

PORTREVISION=	0
CATEGORIES=	audio
PKGNAMESUFFIX=	-ximagesrc

COMMENT=	Gstreamer X source plugin

GST_PLUGIN=	x
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
