# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$
#    $MCom: ports/x11/gstreamer1-plugins-ximagesrc/Makefile,v 1.1 2012/10/06 09:04:19 kwm Exp $

PORTREVISION=	0
CATEGORIES=	audio
PKGNAMESUFFIX=	-ximagesrc

COMMENT=	Gstreamer X source plugin

GST_PLUGIN=	x
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
