# New ports collection makefile for:	gstreamer-plugins-swfdec
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/gstreamer-plugins-swfdec80/Makefile,v 1.1 2006/01/20 02:56:02 ahze Exp $
#

CATEGORIES=	graphics
PORTREVISION=	2

COMMENT=	Gstreamer flash redering plugin

GST_PLUGIN=	swfdec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
