# New ports collection makefile for:	gstreamer-plugins-dts
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/multimedia/gstreamer-plugins-dts/Makefile,v 1.3 2008/02/21 15:33:15 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer dts plugin

GST_PLUGIN=	dts

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
