# New ports collection makefile for:	gstreamer-plugins-cairo
# Date created:			Mar 8 2005
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/graphics/gstreamer-plugins-cairo/Makefile,v 1.4 2008/02/21 16:27:57 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	graphics

COMMENT=	Gstreamer vector graphics plugin

GST_PLUGIN=	cairo

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
