# New ports collection makefile for:	gstreamer-plugins-cairo
# Date created:			Mar 8 2005
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/graphics/gstreamer-plugins-cairo/Makefile,v 1.5 2008/03/15 21:09:33 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	graphics

COMMENT=	Gstreamer vector graphics plugin

GST_PLUGIN=	cairo

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
