# New ports collection makefile for:    totem-xine
# Date created:         March 2, 2007
# Whom:                 Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$

PORTREVISION=	0
PKGNAMESUFFIX=	-xine

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	A XINE-based video player for the GNOME 2 desktop

MASTERDIR=	${.CURDIR}/../totem

WITH_TOTEM_XINE=	yes

CONFLICTS=	totem-[0-9]* totem-gstreamer-[0-9]*

.include "${MASTERDIR}/Makefile"
