# New ports collection makefile for:	gstreamer-plugins-theora
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/multimedia/gstreamer-plugins-theora/Makefile,v 1.1 2008/02/04 15:46:51 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer theora plugin

GST_PLUGIN=	theora

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
