# New ports collection makefile for:	gstreamer-plugins-theora
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/multimedia/gstreamer-plugins-theora/Makefile,v 1.3 2008/03/19 14:05:37 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer theora plugin

GST_PLUGIN=	theora

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
