# New ports collection makefile for:	gstreamer-plugins-faad
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-faad/Makefile,v 1.4 2008/03/15 21:09:28 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer MPEG-2 and MPEG-4 AAC decoder plugin

GST_PLUGIN=	faad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
