# New ports collection makefile for:	gstreamer-plugins-flac
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-flac/Makefile,v 1.3 2008/02/21 16:27:57 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer free lossless audio encoder/decoder plugin

GST_PLUGIN=	flac

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
