# New ports collection makefile for:	gstreamer-plugins-sdl
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/devel/gstreamer-plugins-sdl80/Makefile,v 1.1 2006/01/20 02:55:59 ahze Exp $
#

CATEGORIES=	devel
PORTREVISION=	2

COMMENT=	Gstreamer SDL plugin

GST_PLUGIN=	sdl

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
