# New ports collection makefile for:	gir-repository-gnome-menus
# Date created:				12 September 2009
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	x11

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-gnome-menus

.include "${MASTERDIR}/bsd.gir.mk"
