# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$
#    $MCom: ports/x11/gstreamer1-plugins-x/Makefile,v 1.1 2012/10/06 09:04:19 kwm Exp $

PORTREVISION=	0
CATEGORIES=	x11

COMMENT=	Gstreamer X and Xvideo output plugins

GST_PLUGIN=	x
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
