# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$
#    $MCom$

PORTREVISION=	0
CATEGORIES=	x11

COMMENT=	Gstreamer X and Xvideo output plugins

BROKEN=		needs more work

GST_PLUGIN=	x
DIST=		base

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
