# New ports collection makefile for:	gstreamer-plugins-annodex
# Date created:			6 July 2006
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer annodex CMML plugin

GST_PLUGIN=	annodex

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
