# New ports collection makefile for:	gstreamer-plugins-cdparanoia
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-cdparanoia80/Makefile,v 1.1 2006/01/20 02:55:50 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	3

COMMENT=	Gstreamer CDDA extraction (aka audio ripping) plugin

GST_PLUGIN=	cdparanoia

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
