# New ports collection makefile for:	gstreamer-plugins-mikmod
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-mikmod80/Makefile,v 1.1 2006/01/20 02:55:52 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	Gstreamer mikmod sound plugin

GST_PLUGIN=	mikmod

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
