# New ports collection makefile for:	gstreamer-plugins-faac
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-a52dec80/Makefile,v 1.1 2006/01/20 02:55:49 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	Gstreamer ATSC A/52 stream aka AC-3 (dvd audio) plugin

GST_PLUGIN=	a52dec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
