# New ports collection makefile for:	gstreamer-plugins-flac
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-flac80/Makefile,v 1.1 2006/01/20 02:55:51 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	Gstreamer free lossless audio encoder/decoder plugin

GST_PLUGIN=	flac

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
