# New ports collection makefile for:	gstreamer-plugins-flac
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	audio
PORTREVISION=	1

COMMENT=	Gstreamer free lossless audio encoder/decoder plugin

GST_PLUGIN=	flac

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
