# New ports collection makefile for:	gstreamer-plugins-gconf
# Date created:			10 Mar 2004
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/devel/gstreamer-plugins-gconf/Makefile,v 1.5 2008/03/15 21:09:32 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	devel

COMMENT=	Gstreamer gconf plugin

GST_PLUGIN=	gconf

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
