# New ports collection makefile for:	gstreamer-plugins-libmng
# Date created:			6 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#

PORTREVISION=	1

CATEGORIES=	graphics

GST_PLUGIN=	libmng

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
