# New ports collection makefile for:	gstreamer-plugins-soup
# Date created:			9 Feb 2008
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/devel/gstreamer-plugins-soup/Makefile,v 1.2 2008/03/15 21:09:32 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	devel

COMMENT=	Gstreamer soup http src plugin

GST_PLUGIN=	soup

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
