# New ports collection makefile for:	goocanvas
# Date created:		2006-09-20
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/goocanvas2/Makefile,v 1.4 2011/02/27 14:56:43 kwm Exp $

PORTNAME=	goocanvas
PORTVERSION=	2.0.0
CATEGORIES=	graphics
MASTER_SITES=	GNOME

MAINTAINER=	kwm@FreeBSD.org
COMMENT=	Canvas widget for GTK+ 3

LATEST_LINK=	goocanvas2
USE_GNOME=	gtk30 gnomehack ltverhack
USE_AUTOTOOLS=	libtool
USE_LDCONFIG=	yes
USE_BZIP2=	yes

.include <bsd.port.mk>
