#!/bin/sh
#
# $FreeBSD$
#

case $2 in
DEINSTALL)
	echo ""
	echo "To really remove the dbus port, please remove the following"
	echo "directories manualy:"
	echo ""
	echo "/var/run/dbus /var/db/dbus"
	echo ""
	;;
esac
