# New ports collection makefile for:	gstreamer-plugins-cdparanoia
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-cdparanoia/Makefile,v 1.5 2008/03/19 14:05:28 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer CDDA extraction (aka audio ripping) plugin

GST_PLUGIN=	cdparanoia

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
