# New ports collection makefile for:	gstreamer-plugins-cdparanoia
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-cdparanoia/Makefile,v 1.3 2008/02/04 15:46:49 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer CDDA extraction (aka audio ripping) plugin

GST_PLUGIN=	cdparanoia

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
