# New ports collection makefile for:	gstreamer-plugins-nas
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-nas/Makefile,v 1.3 2008/02/21 15:33:17 kwm Exp $
#

CATEGORIES=	audio
PORTREVISION=	1

COMMENT=	GStreamer NAS (Network Audio System) plugin

GST_PLUGIN=	nas

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
