# New ports collection makefile for:	gstreamer-plugins-nas
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-nas/Makefile,v 1.4 2008/03/15 21:09:30 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	GStreamer NAS (Network Audio System) plugin

GST_PLUGIN=	nas

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
