# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$
#    $MCom$

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer taglib plugin

GST_PLUGIN=	taglib
DIST=		good

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
