# New ports collection makefile for:	gstreamer-plugins-aalib
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	graphics
PORTREVISION=	1

COMMENT=	Gstreamer ascii art plugin

GST_PLUGIN=	aalib

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
