# New ports collection makefile for:	nautilus-open-terminal
# Date created:		2005-07-07
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

PORTNAME=	nautilus-open-terminal
PORTVERSION=	0.2
CATEGORIES=	deskutils
MASTER_SITES=	http://manny.cluecoder.org/packages/nautilus-open-terminal/

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Nautilus extension which allows you to open a terminal

USE_AUTOTOOLS=	libtool:15
USE_GNOME=	nautilus2 gnomeprefix
USE_X_PREFIX=	yes

PLIST_FILES=	lib/nautilus/extensions-1.0/libnautilus-open-terminal.so

.include <bsd.port.mk>
