# New ports collection makefile for:	gir-repository-poppler
# Date created:				07 September 2009
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	graphics

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-poppler

.include "${MASTERDIR}/bsd.gir.mk"
