# New ports collection makefile for:	gstreamer-plugins-gnomevfs
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/devel/gstreamer-plugins-gnomevfs/Makefile,v 1.3 2008/02/04 15:46:49 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	devel

COMMENT=	Gstreamer gnomevfs plugin

GST_PLUGIN=	gnomevfs

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
