# New ports collection makefile for:	gstreamer-plugins-gnomevfs
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/devel/gstreamer-plugins-gnomevfs/Makefile,v 1.4 2008/03/15 21:09:32 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	devel

COMMENT=	Gstreamer gnomevfs plugin

GST_PLUGIN=	gnomevfs

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
