# New ports collection makefile for:    librsvg2
# Date created:         		8th May 2001
# Whom:                 		Ade Lovett <ade@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/graphics/librsvg2/Makefile,v 1.131 2010/05/02 10:25:51 kwm Exp $
#

PORTREVISION=	0

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Gtk 3 engine for the librsvg2 library

MASTERDIR=	${.CURDIR}/../../graphics/librsvg2
SLAVEPORT=	gtk3
PLIST=  ${.CURDIR}/pkg-plist

.include <${MASTERDIR}/Makefile>
