# New ports collection makefile for:	gstreamer-plugins-libvisual
# Date created:			4 Dec 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/graphics/gstreamer-plugins-libvisual/Makefile,v 1.5 2008/03/19 14:05:35 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer libvisual plugin

GST_PLUGIN=	libvisual

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
