# New ports collection makefile for:	ArialUni CJK TrueType fonts
# Date created:		13 Oct 2001
# Whom:			Shen Chuan-Hsing <statue@freebsd.sinica.edu.tw>
#
# $FreeBSD: ports/chinese/xttmgr/Makefile,v 1.5 2005/07/25 21:58:10 linimon Exp $
#

PORTNAME=	xttmgr
PORTVERSION=	0.9.6
CATEGORIES=	chinese
MASTER_SITES=	ftp://freebsd.sinica.edu.tw/pub/statue/xttmgr/

MAINTAINER=	ports@FreeBSD.org
COMMENT=	A Big5/GB enhanced TrueType Font Manager

BUILD_DEPENDS=	freetype-config:${PORTSDIR}/print/freetype2

PLIST_FILES=	bin/xttmgr

.include <bsd.port.mk>
