# New ports collection makefile for:	gstreamer-plugins-xvid
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/multimedia/gstreamer-plugins-xvid/Makefile,v 1.3 2008/02/21 15:33:19 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	multimedia

COMMENT=	Gstreamer xvid plugin

GST_PLUGIN=	xvid

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
