# New ports collection makefile for:	gstreamer-plugins-spc
# Date created:			22 Dec 2006
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-spc/Makefile,v 1.1 2008/02/21 15:33:18 kwm Exp $

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer OpenSPC frontend

GST_PLUGIN=	spc

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
