# New ports collection makefile for:	gstreamer-plugins-polypaudio
# Date created:			8 Dec 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-polyp80/Makefile,v 1.2 2006/02/23 18:05:33 marcus Exp $
#

CATEGORIES=	audio
PORTREVISION=	3

COMMENT=	Gstreamer polypaudio sound server plugin

GST_PLUGIN=	polyp

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
