# New ports collection makefile for:	gir-repository-gstreamer
# Date created:				12 September 2009
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	multimedia

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-gstreamer

.include "${MASTERDIR}/bsd.gir.mk"
