# New ports collection makefile for:	gstreamer-plugins-cdaudio
# Date created:			17 Dec 2004
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	audio
PORTREVISION=	1

COMMENT=	Gstreamer audio cd playing plugin

GST_PLUGIN=	cdaudio

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
