# $FreeBSD$

PORTREVISION=	0
CATEGORIES=	multimedia

COMMENT=	Gstreamer curl plugin

GST_PLUGIN=	curl
DIST=		bad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
