# New ports collection makefile for:	gstreamer-plugins-libmms
# Date created:			8 March 2005
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/net/gstreamer-plugins-libmms80/Makefile,v 1.1 2006/01/20 02:56:12 ahze Exp $
#

CATEGORIES=	net
PORTREVISION=	2

COMMENT=	Gstreamer mms:// and mmsh:// plugin

GST_PLUGIN=	libmms

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
