# New ports collection makefile for:	gstreamer-plugins-libvisual
# Date created:			4 Dec 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/gstreamer-plugins-libvisual80/Makefile,v 1.1 2006/01/20 02:56:02 ahze Exp $
#

CATEGORIES=	graphics
PORTREVISION=	2

COMMENT=	Gstreamer libvisual plugin

GST_PLUGIN=	libvisual

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
