# New ports collection makefile for:	gstreamer-plugins-libvisual
# Date created:			4 Dec 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	graphics
PORTREVISION=	1

COMMENT=	Gstreamer libvisual plugin

GST_PLUGIN=	libvisual

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
