# New ports collection makefile for:	gstreamer-plugins-mpeg2dec
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/multimedia/gstreamer-plugins-mpeg2dec/Makefile,v 1.4 2008/03/15 21:09:36 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	Gstreamer mpeg decode plugin

GST_PLUGIN=	mpeg2dec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
