# New ports collection makefile for:	gstreamer-plugins-gdkpixbuf
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/gstreamer-plugins-gdkpixbuf80/Makefile,v 1.1 2006/01/20 02:56:01 ahze Exp $
#

CATEGORIES=	graphics
PORTREVISION=	2

COMMENT=	Gstreamer image decoder plugin

GST_PLUGIN=	gdkpixbuf

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
