# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$
#   $MCom$

PORTNAME=	gnome-video-effects
PORTVERSION=	0.4.0
CATEGORIES=	graphics
MASTER_SITES=	GNOME

MAINTAINER=	kwm@FreeBSD.org
COMMENT=	Collection of Gstreamer effects

USE_GNOME=	intlhack
USES=		gettext gmake pathfix tar:xz
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
