# Created by: Koop Mast <kwm@FreeBSD.org>
# $FreeBSD$
#   $MCom: ports/trunk/graphics/gnome-video-effects/Makefile 18393 2013-04-26 21:23:07Z kwm $

PORTNAME=	gnome-video-effects
PORTVERSION=	0.3.0
CATEGORIES=	graphics
MASTER_SITES=	GNOME

MAINTAINER=	kwm@FreeBSD.org
COMMENT=	A collection of Gstreamer effects

USE_BZIP2=	yes
USE_GNOME=	intlhack
USES=		gettext gmake pathfix
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
