# New ports collection makefile for:	poppler-qt
# Date created:		2006-01-12
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/poppler-qt/Makefile,v 1.5 2006/03/09 01:49:50 marcus Exp $

PORTREVISION=	0
PKGNAMESUFFIX=	-qt

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Qt bindings to poppler

MASTERDIR=	${.CURDIR}/../../graphics/poppler
SLAVEPORT=	qt
PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
