# New ports collection makefile for:	gstreamer-plugins-dts
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	multimedia
PORTREVISION=	1

COMMENT=	Gstreamer dts plugin

GST_PLUGIN=	dts

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
