# New ports collection makefile for:	gstreamer-plugins-mad
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	Gstreamer mp3 decoder plugin

GST_PLUGIN=	mad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
