# New ports collection makefile for:	gstreamer-plugins-mad
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-mad80/Makefile,v 1.1 2006/01/20 02:55:52 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	3

COMMENT=	Gstreamer mp3 decoder plugin

GST_PLUGIN=	mad

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
