# New ports collection makefile for:	gstreamer-plugins-swfdec
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/gstreamer-plugins-swfdec/Makefile,v 1.4 2008/03/15 21:09:34 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	graphics

COMMENT=	Gstreamer flash redering plugin

GST_PLUGIN=	swfdec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

BROKEN=		Does not compile

.include "${MASTERDIR}/Makefile"
