# New ports collection makefile for:	gstreamer-plugins-swfdec
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/gstreamer-plugins-swfdec/Makefile,v 1.3 2008/02/21 15:33:18 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	graphics

COMMENT=	Gstreamer flash redering plugin

GST_PLUGIN=	swfdec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

BROKEN=		Does not compile

.include "${MASTERDIR}/Makefile"
