# New ports collection makefile for:	gstreamer-plugins-swfdec
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer flash redering plugin

GST_PLUGIN=	swfdec

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

BROKEN=		Does not compile

.include "${MASTERDIR}/Makefile"
