# New ports collection makefile for:	gstreamer-plugins-ogg
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	audio
PORTREVISION=	1

COMMENT=	Gstreamer Ogg bitstream plugin

GST_PLUGIN=	ogg

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
