# New ports collection makefile for:	gstreamer-plugins-gconf
# Date created:			10 Mar 2004
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/devel/gstreamer-plugins-gconf80/Makefile,v 1.1 2006/01/20 02:55:58 ahze Exp $
#

CATEGORIES=	devel
PORTREVISION=	2

COMMENT=	Gstreamer gconf plugin

GST_PLUGIN=	gconf

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
