# New ports collection makefile for:	gstreamer-plugins-smoothwave
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	audio
PORTREVISION=	1

COMMENT=	Gstreamer visualisation plugin

GST_PLUGIN=	smoothwave

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
