# New ports collection makefile for:	gstreamer-plugins-x264
# Date created:			6 Sep 2005
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/multimedia/gstreamer-plugins-x264/Makefile,v 1.1 2008/02/21 15:33:18 kwm Exp $
#

CATEGORIES=	multimedia
PORTREVISION=	1

COMMENT=	Gstreamer x264 plugin

GST_PLUGIN=	x264

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
