# New ports collection makefile for:	gstreamer-plugins-shout2
# Date created:			16 Mar 2005
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-shout2/Makefile,v 1.1 2008/02/21 16:27:59 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer icecast plugin

GST_PLUGIN=	shout2

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
