# Created by: FreeBSD GNOME Team <gnome@freebsd.org>
# $FreeBSD$
#   $MCom$

PORTNAME=	vala-vapigen
PORTVERSION=	0.26.1	# keep the version in sync with vala
CATEGORIES=	lang gnome
MASTER_SITES=	# empty
DISTFILES=	# empty
EXTRACT_ONLY=	# empty

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Dummy port that brings in vala-vapigen

RUN_DEPENDS=	vala:${PORTSDIR}/lang/vala

NO_INSTALL=	yes
NO_BUILD=	yes

.include <bsd.port.mk>
