--- libgnetwork/gnetwork-interfaces.h.orig	Thu Dec 11 21:17:13 2003
+++ libgnetwork/gnetwork-interfaces.h	Fri Dec 12 01:42:17 2003
@@ -23,6 +23,8 @@
 #define __GNETWORK_INTERFACES_H__
 
 #include <glib-object.h>
+#include <sys/types.h>
+#include <sys/socket.h>
 #include <net/if.h>
 
 G_BEGIN_DECLS
@@ -45,16 +47,32 @@
   /* Special Types */
   GNETWORK_INTERFACE_IS_LOOPBACK = IFF_LOOPBACK,
   GNETWORK_INTERFACE_IS_POINT_TO_POINT = IFF_POINTOPOINT,
+#ifdef IFF_MASTER
   GNETWORK_INTERFACE_IS_LOAD_MASTER = IFF_MASTER,
+#endif
+#ifdef IFF_SLAVE
   GNETWORK_INTERFACE_IS_LOAD_SLAVE = IFF_SLAVE,
+#endif
 
   /* Capabilities */
   GNETWORK_INTERFACE_CAN_BROADCAST = IFF_BROADCAST,
   GNETWORK_INTERFACE_CAN_MULTICAST = IFF_MULTICAST,
+#ifdef IFF_NOTRAILERS
   GNETWORK_INTERFACE_NO_TRAILERS = IFF_NOTRAILERS,
+#endif
   GNETWORK_INTERFACE_NO_ARP = IFF_NOARP,
+#ifdef IFF_PORTSEL
   GNETWORK_INTERFACE_CAN_SET_MEDIA = IFF_PORTSEL,
+#endif
+#ifdef IFF_ALTPHYS
+  GNETWORK_INTERFACE_CAN_MANAGE_ROUTES = IFF_ALTPHYS,
+#endif
+#ifdef IFF_ALTPHYS
+  GNETWORK_INTERFACE_ALT_CONN = IFF_ALTPHYS,
+#endif
+#ifdef IFF_AUTOMEDIA
   GNETWORK_INTERFACE_AUTOSELECTED_MEDIA = IFF_AUTOMEDIA,
+#endif
 
   /* Modes */
   GNETWORK_INTERFACE_RECV_ALL_PACKETS = IFF_PROMISC,
