# New ports collection makefile for:	gir-repository-nautilus
# Date created:				12 September 2009
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	x11-fm

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-nautilus

.include "${MASTERDIR}/bsd.gir.mk"
