# New ports collection makefile for:	gstreamer-plugins-dv
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/multimedia/gstreamer-plugins-dv/Makefile,v 1.4 2008/03/15 21:09:35 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	multimedia

COMMENT=	Gstreamer dv plugin

GST_PLUGIN=	dv

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
