# New ports collection makefile for:	gstreamer-plugins-sidplay
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/audio/gstreamer-plugins-sidplay80/Makefile,v 1.1 2006/01/20 02:55:54 ahze Exp $
#

CATEGORIES=	audio
PORTREVISION=	2

COMMENT=	Gstreamer Commodore SID decoder plugin

GST_PLUGIN=	sidplay

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
