# $FreeBSD$

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer OpenCore based Adaptive Multi-Rate Wide-Band Decoder plugin

GST_PLUGIN=	amrwb
DIST=		ugly

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer1-plugins

.include "${MASTERDIR}/Makefile"
