# New ports collection makefile for:	gstreamer-plugins-jpeg
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/graphics/gstreamer-plugins-jpeg/Makefile,v 1.4 2008/03/15 21:09:33 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	graphics

COMMENT=	Gstreamer jpeg encoder/decoder plugin

GST_PLUGIN=	jpeg

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
