# New ports collection makefile for:	webkit-qt4
# Date created:		2007-10-22
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/www/webkit-qt4/Makefile,v 1.1 2007/11/02 12:51:18 ahze Exp $

PKGNAMESUFFIX=	-qt4

MASTERDIR=	${.CURDIR}/../../www/webkit-gtk2

WEBKIT_SLAVE=	qt4
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
