# New ports collection makefile for:	gstreamer-plugins-libmms
# Date created:			8 March 2005
# Whom:				Koop Mast <kwm@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

PORTREVISION=	0
CATEGORIES=	net

COMMENT=	Gstreamer mms:// and mmsh:// plugin

GST_PLUGIN=	libmms

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
