# New ports collection makefile for:	gstreamer-plugins-ogg
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-ogg/Makefile,v 1.5 2008/03/19 14:05:31 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer Ogg bitstream plugin

GST_PLUGIN=	ogg

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
