# New ports collection makefile for:	gstreamer-plugins-jpeg
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	graphics
PORTREVISION=	1

COMMENT=	Gstreamer jpeg encoder/decoder plugin

GST_PLUGIN=	jpeg

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
