# New ports collection makefile for:	gnomecommon
# Date created:				04 April 2002
# Whom:					Joe Marcus Clarke <marcus@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/devel/gnome-common/Makefile,v 1.17 2011/04/04 08:56:31 kwm Exp $
#

PORTNAME=	gnome-common
PORTVERSION=	3.4.0.1
CATEGORIES=	devel
MASTER_SITES=	GNOME
DIST_SUBDIR=	gnome2

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Common automake macros for GNOME 2 and GNOME 3

USE_XZ=		yes
USE_GMAKE=	yes
USE_GNOME=	pkgconfig
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
