# Created by: Joe Marcus Clarke <marcus@FreeBSD.org>
# $FreeBSD$
#    $MCom$

PORTNAME=	gnome-common
PORTVERSION=	3.6.0
CATEGORIES=	devel
MASTER_SITES=	GNOME
DIST_SUBDIR=	gnome2

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Common automake macros for GNOME 2 and GNOME 3

USE_XZ=		yes
USE_GMAKE=	yes
USES=		pkgconfig
GNU_CONFIGURE=	yes

.include <bsd.port.mk>
