# New ports collection makefile for:	gstreamer-plugins-speex
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-speex/Makefile,v 1.3 2008/02/21 16:27:59 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	audio

COMMENT=	Gstreamer speex voice plugin

GST_PLUGIN=	speex

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
