# New ports collection makefile for:	poppler-qt4
# Date created:		June 26, 2007
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$

PORTREVISION=	0
PKGNAMESUFFIX=	-qt4

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Qt4 bindings to poppler

MASTERDIR=	${.CURDIR}/../../graphics/poppler
SLAVEPORT=	qt4
PLIST=	${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
