# New ports collection makefile for:	poppler-qt4
# Date created:		June 26, 2007
# Whom:			Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/graphics/poppler-qt4/Makefile,v 1.9 2009/05/17 05:48:50 marcus Exp $
#

PORTREVISION=	1
PKGNAMESUFFIX=	-qt4

MAINTAINER=	gnome@FreeBSD.org
COMMENT=	Qt4 bindings to poppler

MASTERDIR=	${.CURDIR}/../../graphics/poppler
SLAVEPORT=	qt4
PLIST=		${.CURDIR}/pkg-plist

.include "${MASTERDIR}/Makefile"
