# New ports collection makefile for:	gir-repository-gtksourceview2
# Date created:				12 September 2009
# Whom:					Alexander Logvinov <avl@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

CATEGORIES=	x11-toolkits

MASTERDIR=	${.CURDIR}/../../devel/gir-repository

PKGNAMESUFFIX=	-gtksourceview2

.include "${MASTERDIR}/bsd.gir.mk"
