# New ports collection makefile for:	gstreamer-plugins-pango
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/x11-toolkits/gstreamer-plugins-pango/Makefile,v 1.5 2008/03/19 14:05:38 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	x11-toolkits

COMMENT=	Gstreamer pango textoverlay plugin

GST_PLUGIN=	pango

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
