# New ports collection makefile for:	gstreamer-plugins-cairo
# Date created:			Mar 8 2005
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom: ports/graphics/gstreamer-plugins-cairo80/Makefile,v 1.1 2006/01/20 02:56:00 ahze Exp $
#   $MCom: ports/graphics/gstreamer-plugins-cairo80/Makefile,v 1.1 2006/01/20 02:56:00 ahze Exp $
#

CATEGORIES=	graphics
PORTREVISION=	2

COMMENT=	Gstreamer vector graphics plugin

GST_PLUGIN=	cairo

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
