# New ports collection makefile for:	gstreamer-plugins-faac
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#    $MCom$
#

CATEGORIES=	audio
PORTREVISION=	1

COMMENT=	Gstreamer MPEG-2 and MPEG-4 AAC encoder plugin

GST_PLUGIN=	faac

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins80

.include "${MASTERDIR}/Makefile"
