# New ports collection makefile for:	gstreamer-plugins-vorbis
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-vorbis/Makefile,v 1.4 2008/03/15 21:09:31 ahze Exp $
#

PORTREVISION=	2
CATEGORIES=	audio

COMMENT=	Gstreamer vorbis encoder/decoder plugin

GST_PLUGIN=	vorbis

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
