# New ports collection makefile for:	gstreamer-plugins-vorbis
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/audio/gstreamer-plugins-vorbis/Makefile,v 1.5 2008/03/19 14:05:32 ahze Exp $
#

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer vorbis encoder/decoder plugin

GST_PLUGIN=	vorbis

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
