# New ports collection makefile for:	gstreamer-plugins-vorbis
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

PORTREVISION=	0
CATEGORIES=	audio

COMMENT=	Gstreamer vorbis encoder/decoder plugin

GST_PLUGIN=	vorbis

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
