# New ports collection makefile for:	gstreamer-plugins-gdkpixbuf
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom: ports/graphics/gstreamer-plugins-gdkpixbuf/Makefile,v 1.3 2008/02/21 16:27:58 kwm Exp $
#

PORTREVISION=	1
CATEGORIES=	graphics

COMMENT=	Gstreamer image decoder plugin

GST_PLUGIN=	gdk_pixbuf

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
