# New ports collection makefile for:	gstreamer-plugins-gdkpixbuf
# Date created:			3 Oct 2004
# Whom:				Michael Johnson <ahze@FreeBSD.org>
#
# $FreeBSD$
#   $MCom$
#

PORTREVISION=	0
CATEGORIES=	graphics

COMMENT=	Gstreamer image decoder plugin

GST_PLUGIN=	gdk_pixbuf

MASTERDIR=	${.CURDIR}/../../multimedia/gstreamer-plugins

.include "${MASTERDIR}/Makefile"
